#' homozyg_snp
#' 
#' homozyg_snp() calculates the minimum number of SNPs to have less than 5% of
#' ROH generated by chance (l) (Lencz et al., 2007)
#'
#' @param hardy_path a .hwe file generated by the --hardy function in PLINK
#' @param ni the number of individuals
#'
#' @return l
#' @export
#'
#' @examples
homozyg_snp <- function(hardy_path,ni) {
  dataset_hardy <- read.table(hardy_path, sep= "", header = TRUE)
  Hm <- mean(dataset_hardy$O.HET., na.rm = TRUE) #Hm is the average observed heterozygosity
  ns <- nrow(dataset_hardy) #ns is the number of SNPs per individual
  ni <- as.numeric(ni)
  l <- log(0.05 / (ns- ni)) / log(1- Hm)
  return(l)
}