#' homozyg_snp
#' 
#' A function that calculates the minimum number of SNPs to have less than 5% of ROH generated by chance (l) (Lencz et al., 2007)
#'
#' @param hardy_path a .hwe file generated by the --hardy function in PLINK
#' @param ni the number of individuals
#'
#' @return l
#' @export
#'
#' @examples
homozyg_snp <- function(hardy_path,ni) {
  dataset_hardy <- read.table(hardy_path, sep= "", header = TRUE)
  Hm <- mean(dataset_hardy$O.HET., na.rm = TRUE) #Hm is the average observed heterozygosity
  ns <- nrow(dataset_hardy) #ns is the number of SNPs per individual
  ni <- as.numeric(ni)
  l <- log(0.05 / (ns- ni)) / log(1- Hm)
  return(l)
}


## TODO: later add examples


#' homozyg_density
#'
#'A function that determines the minimum SNP density (in Mb) for the segment to be considered ROH.
#' @param bim_path a PLINK .bim file
#'
#' @return snp_density
#' @export
#'
#' @examples
homozyg_density <- function(bim_path) {
  bim_file <- read.table(bim_path, sep = "\t", header = FALSE)
  snp_nb <- nrow(bim_file)
  covered_genome_size =0
  for (i in 1:22) {
    dataset_chr_i<-bim_file[ bim_file$V1 == i, ]
    size_chr_i <- max(dataset_chr_i$V4, na.rm = FALSE) - min(dataset_chr_i$V4, na.rm = FALSE)
    covered_genome_size <- covered_genome_size + size_chr_i
  }
  couverage <- covered_genome_size
  density <- snp_nb/couverage *1000
  snp_density <- 1 / density
  return(snp_density)
}


