#' Script for ROH_identification
#' homozyg_snp funtion calculates the minimum number of SNPs to have less than 5% of ROH generated by chance (l) (Lencz et al., 2007)
#' @param hardy_path a PLINK .hwe file obtained by the --hardy function
#' @param ni number of individuals
#' @return (l)
homozyg_snp <- function(hardy_path,ni) {
  dataset_hardy <- read.table(hardy_path, sep= "", header = TRUE)
  Hm <- mean(dataset_hardy$O.HET., na.rm = TRUE) #Hm is the average observed heterozygosity
  ns <- nrow(dataset_hardy) #ns is the number of SNPs per individual
  ni <- as.numeric(ni)
  l <- log(0.05 / (ns- ni)) / log(1- Hm)
  return(l)
}
######################################
#####################################
####################################
#' The homozyg_density function determines the minimum SNP density(in Mb) for the segment to be considered ROH
#' this funtion calculates the size of the covered genome and then divides the number of snp by the couverage
#' @param bim_path a PLINK .bim file
#' @return snp density
homozyg_density <- function(bim_path) {
  bim_file <- read.table(bim_path, sep = "\t", header = FALSE)
  snp_nb <- nrow(bim_file)
  covered_genome_size =0
  for (i in 1:22) {
    dataset_chr_i<-bim_file[ bim_file$V1 == i, ]
    size_chr_i <- max(dataset_chr_i$V4, na.rm = FALSE) - min(dataset_chr_i$V4, na.rm = FALSE)
    covered_genome_size <- covered_genome_size + size_chr_i
  }
  couverage <- covered_genome_size
  density <- snp_nb/couverage *1000
  snp_density <- 1 / density
  return(snp_density)
}

homozyg_density("C:/Users/Lenovo/Desktop/merging/final_dataset/all_populations.bim")
homozyg_snp("C:/Users/Lenovo/Desktop/ANALYSE ROH MASTER/WORLD_POPULATION_DATA/merge/QC/hardy_lebanon.hwe",75)


